/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../syncEngine/utils`; params?: Router.UnknownInputParams; } | { pathname: `/../syncEngine/push`; params?: Router.UnknownInputParams; } | { pathname: `/../syncEngine/pull`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}/charts` | `/charts`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}/log` | `/log`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(supervisor)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(supervisor)'}/patients` | `/patients`; params?: Router.UnknownInputParams; } | { pathname: `${'/(supervisor)'}/settings` | `/settings`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../syncEngine/utils`; params?: Router.UnknownOutputParams; } | { pathname: `/../syncEngine/push`; params?: Router.UnknownOutputParams; } | { pathname: `/../syncEngine/pull`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(patient)'}/charts` | `/charts`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(patient)'}/history` | `/history`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(patient)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(patient)'}/log` | `/log`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(patient)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(supervisor)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(supervisor)'}/patients` | `/patients`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(supervisor)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/../syncEngine/utils${`?${string}` | `#${string}` | ''}` | `/../syncEngine/push${`?${string}` | `#${string}` | ''}` | `/../syncEngine/pull${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(patient)'}/charts${`?${string}` | `#${string}` | ''}` | `/charts${`?${string}` | `#${string}` | ''}` | `${'/(patient)'}/history${`?${string}` | `#${string}` | ''}` | `/history${`?${string}` | `#${string}` | ''}` | `${'/(patient)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(patient)'}/log${`?${string}` | `#${string}` | ''}` | `/log${`?${string}` | `#${string}` | ''}` | `${'/(patient)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `${'/(supervisor)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(supervisor)'}/patients${`?${string}` | `#${string}` | ''}` | `/patients${`?${string}` | `#${string}` | ''}` | `${'/(supervisor)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../syncEngine/utils`; params?: Router.UnknownInputParams; } | { pathname: `/../syncEngine/push`; params?: Router.UnknownInputParams; } | { pathname: `/../syncEngine/pull`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}/charts` | `/charts`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}/log` | `/log`; params?: Router.UnknownInputParams; } | { pathname: `${'/(patient)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(supervisor)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(supervisor)'}/patients` | `/patients`; params?: Router.UnknownInputParams; } | { pathname: `${'/(supervisor)'}/settings` | `/settings`; params?: Router.UnknownInputParams; };
    }
  }
}
